//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.NotificationPoller {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DaDeskEventNotificationsType", Namespace="http://www.dadesk.com/dis/schema", ItemName="daDeskEventNotification")]
    [System.SerializableAttribute()]
    public class DaDeskEventNotificationsType : System.Collections.Generic.List<WindowsFormsApplication1.NotificationPoller.DaDeskEventNotificationType> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DaDeskEventNotificationType", Namespace="http://www.dadesk.com/dis/schema")]
    [System.SerializableAttribute()]
    public partial class DaDeskEventNotificationType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int principleIdField;
        
        private string interfaceUniqueReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int portCallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.NotificationPoller.DaApprovalNotificationType DaApprovalNotificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.NotificationPoller.CancelPortcallNotificationType cancelPortcallNotificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.NotificationPoller.UpdatePortcallNotificationType updatePortcallNotificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.NotificationPoller.AgentAppointmentNotificationType agentAppointmentNotificationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int principleId {
            get {
                return this.principleIdField;
            }
            set {
                if ((this.principleIdField.Equals(value) != true)) {
                    this.principleIdField = value;
                    this.RaisePropertyChanged("principleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string interfaceUniqueReference {
            get {
                return this.interfaceUniqueReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.interfaceUniqueReferenceField, value) != true)) {
                    this.interfaceUniqueReferenceField = value;
                    this.RaisePropertyChanged("interfaceUniqueReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int portCallId {
            get {
                return this.portCallIdField;
            }
            set {
                if ((this.portCallIdField.Equals(value) != true)) {
                    this.portCallIdField = value;
                    this.RaisePropertyChanged("portCallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WindowsFormsApplication1.NotificationPoller.DaApprovalNotificationType DaApprovalNotification {
            get {
                return this.DaApprovalNotificationField;
            }
            set {
                if ((object.ReferenceEquals(this.DaApprovalNotificationField, value) != true)) {
                    this.DaApprovalNotificationField = value;
                    this.RaisePropertyChanged("DaApprovalNotification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WindowsFormsApplication1.NotificationPoller.CancelPortcallNotificationType cancelPortcallNotification {
            get {
                return this.cancelPortcallNotificationField;
            }
            set {
                if ((object.ReferenceEquals(this.cancelPortcallNotificationField, value) != true)) {
                    this.cancelPortcallNotificationField = value;
                    this.RaisePropertyChanged("cancelPortcallNotification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WindowsFormsApplication1.NotificationPoller.UpdatePortcallNotificationType updatePortcallNotification {
            get {
                return this.updatePortcallNotificationField;
            }
            set {
                if ((object.ReferenceEquals(this.updatePortcallNotificationField, value) != true)) {
                    this.updatePortcallNotificationField = value;
                    this.RaisePropertyChanged("updatePortcallNotification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WindowsFormsApplication1.NotificationPoller.AgentAppointmentNotificationType agentAppointmentNotification {
            get {
                return this.agentAppointmentNotificationField;
            }
            set {
                if ((object.ReferenceEquals(this.agentAppointmentNotificationField, value) != true)) {
                    this.agentAppointmentNotificationField = value;
                    this.RaisePropertyChanged("agentAppointmentNotification");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DaApprovalNotificationType", Namespace="http://www.dadesk.com/dis/schema")]
    [System.SerializableAttribute()]
    public partial class DaApprovalNotificationType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string invoiceIdField;
        
        private string daReferenceField;
        
        private string daTypeField;
        
        private string daEventField;
        
        private WindowsFormsApplication1.NotificationPoller.actorType actorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string invoiceId {
            get {
                return this.invoiceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.invoiceIdField, value) != true)) {
                    this.invoiceIdField = value;
                    this.RaisePropertyChanged("invoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string daReference {
            get {
                return this.daReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.daReferenceField, value) != true)) {
                    this.daReferenceField = value;
                    this.RaisePropertyChanged("daReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string daType {
            get {
                return this.daTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.daTypeField, value) != true)) {
                    this.daTypeField = value;
                    this.RaisePropertyChanged("daType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string daEvent {
            get {
                return this.daEventField;
            }
            set {
                if ((object.ReferenceEquals(this.daEventField, value) != true)) {
                    this.daEventField = value;
                    this.RaisePropertyChanged("daEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public WindowsFormsApplication1.NotificationPoller.actorType actor {
            get {
                return this.actorField;
            }
            set {
                if ((object.ReferenceEquals(this.actorField, value) != true)) {
                    this.actorField = value;
                    this.RaisePropertyChanged("actor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelPortcallNotificationType", Namespace="http://www.dadesk.com/dis/schema")]
    [System.SerializableAttribute()]
    public partial class CancelPortcallNotificationType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string portCallStateField;
        
        private WindowsFormsApplication1.NotificationPoller.actorType actorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string portCallState {
            get {
                return this.portCallStateField;
            }
            set {
                if ((object.ReferenceEquals(this.portCallStateField, value) != true)) {
                    this.portCallStateField = value;
                    this.RaisePropertyChanged("portCallState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public WindowsFormsApplication1.NotificationPoller.actorType actor {
            get {
                return this.actorField;
            }
            set {
                if ((object.ReferenceEquals(this.actorField, value) != true)) {
                    this.actorField = value;
                    this.RaisePropertyChanged("actor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdatePortcallNotificationType", Namespace="http://www.dadesk.com/dis/schema")]
    [System.SerializableAttribute()]
    public partial class UpdatePortcallNotificationType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WindowsFormsApplication1.NotificationPoller.actorType actorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.NotificationPoller.ETAchangeType ETAchangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.NotificationPoller.agentChangeType agentChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.NotificationPoller.portChangeType portChangeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public WindowsFormsApplication1.NotificationPoller.actorType actor {
            get {
                return this.actorField;
            }
            set {
                if ((object.ReferenceEquals(this.actorField, value) != true)) {
                    this.actorField = value;
                    this.RaisePropertyChanged("actor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WindowsFormsApplication1.NotificationPoller.ETAchangeType ETAchange {
            get {
                return this.ETAchangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ETAchangeField, value) != true)) {
                    this.ETAchangeField = value;
                    this.RaisePropertyChanged("ETAchange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WindowsFormsApplication1.NotificationPoller.agentChangeType agentChange {
            get {
                return this.agentChangeField;
            }
            set {
                if ((object.ReferenceEquals(this.agentChangeField, value) != true)) {
                    this.agentChangeField = value;
                    this.RaisePropertyChanged("agentChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WindowsFormsApplication1.NotificationPoller.portChangeType portChange {
            get {
                return this.portChangeField;
            }
            set {
                if ((object.ReferenceEquals(this.portChangeField, value) != true)) {
                    this.portChangeField = value;
                    this.RaisePropertyChanged("portChange");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentAppointmentNotificationType", Namespace="http://www.dadesk.com/dis/schema")]
    [System.SerializableAttribute()]
    public partial class AgentAppointmentNotificationType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string invoiceIdField;
        
        private string daReferenceField;
        
        private string daTypeField;
        
        private string daEventField;
        
        private WindowsFormsApplication1.NotificationPoller.actorType actorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string invoiceId {
            get {
                return this.invoiceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.invoiceIdField, value) != true)) {
                    this.invoiceIdField = value;
                    this.RaisePropertyChanged("invoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string daReference {
            get {
                return this.daReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.daReferenceField, value) != true)) {
                    this.daReferenceField = value;
                    this.RaisePropertyChanged("daReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string daType {
            get {
                return this.daTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.daTypeField, value) != true)) {
                    this.daTypeField = value;
                    this.RaisePropertyChanged("daType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string daEvent {
            get {
                return this.daEventField;
            }
            set {
                if ((object.ReferenceEquals(this.daEventField, value) != true)) {
                    this.daEventField = value;
                    this.RaisePropertyChanged("daEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public WindowsFormsApplication1.NotificationPoller.actorType actor {
            get {
                return this.actorField;
            }
            set {
                if ((object.ReferenceEquals(this.actorField, value) != true)) {
                    this.actorField = value;
                    this.RaisePropertyChanged("actor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="actorType", Namespace="http://www.dadesk.com/dis/schema")]
    [System.SerializableAttribute()]
    public partial class actorType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string actorIDField;
        
        private System.DateTime actionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actorLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string actorID {
            get {
                return this.actorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.actorIDField, value) != true)) {
                    this.actorIDField = value;
                    this.RaisePropertyChanged("actorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime actionDate {
            get {
                return this.actionDateField;
            }
            set {
                if ((this.actionDateField.Equals(value) != true)) {
                    this.actionDateField = value;
                    this.RaisePropertyChanged("actionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string actorLevel {
            get {
                return this.actorLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.actorLevelField, value) != true)) {
                    this.actorLevelField = value;
                    this.RaisePropertyChanged("actorLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETAchangeType", Namespace="http://www.dadesk.com/dis/schema")]
    [System.SerializableAttribute()]
    public partial class ETAchangeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime originalETAField;
        
        private System.DateTime newETAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime originalETA {
            get {
                return this.originalETAField;
            }
            set {
                if ((this.originalETAField.Equals(value) != true)) {
                    this.originalETAField = value;
                    this.RaisePropertyChanged("originalETA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime newETA {
            get {
                return this.newETAField;
            }
            set {
                if ((this.newETAField.Equals(value) != true)) {
                    this.newETAField = value;
                    this.RaisePropertyChanged("newETA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="agentChangeType", Namespace="http://www.dadesk.com/dis/schema")]
    [System.SerializableAttribute()]
    public partial class agentChangeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string originalAgentIDField;
        
        private string newAgentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string originalAgentID {
            get {
                return this.originalAgentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.originalAgentIDField, value) != true)) {
                    this.originalAgentIDField = value;
                    this.RaisePropertyChanged("originalAgentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string newAgentID {
            get {
                return this.newAgentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.newAgentIDField, value) != true)) {
                    this.newAgentIDField = value;
                    this.RaisePropertyChanged("newAgentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="portChangeType", Namespace="http://www.dadesk.com/dis/schema")]
    [System.SerializableAttribute()]
    public partial class portChangeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string originalPortIDField;
        
        private string newPortIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string originalPortID {
            get {
                return this.originalPortIDField;
            }
            set {
                if ((object.ReferenceEquals(this.originalPortIDField, value) != true)) {
                    this.originalPortIDField = value;
                    this.RaisePropertyChanged("originalPortID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string newPortID {
            get {
                return this.newPortIDField;
            }
            set {
                if ((object.ReferenceEquals(this.newPortIDField, value) != true)) {
                    this.newPortIDField = value;
                    this.RaisePropertyChanged("newPortID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="loginType", Namespace="http://www.marcura.com/dis/notifications/schema")]
    [System.SerializableAttribute()]
    public partial class loginType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string usernameField;
        
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userType", Namespace="http://www.marcura.com/dis/notifications/schema")]
    [System.SerializableAttribute()]
    public partial class userType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string usernameField;
        
        private string fullNameField;
        
        private string emailField;
        
        private WindowsFormsApplication1.NotificationPoller.userType.companyType companyField;
        
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameField, value) != true)) {
                    this.fullNameField = value;
                    this.RaisePropertyChanged("fullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public WindowsFormsApplication1.NotificationPoller.userType.companyType company {
            get {
                return this.companyField;
            }
            set {
                if ((object.ReferenceEquals(this.companyField, value) != true)) {
                    this.companyField = value;
                    this.RaisePropertyChanged("company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="userType.companyType", Namespace="http://www.marcura.com/dis/notifications/schema")]
        [System.SerializableAttribute()]
        public partial class companyType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private long idField;
            
            private string nameField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public long id {
                get {
                    return this.idField;
                }
                set {
                    if ((this.idField.Equals(value) != true)) {
                        this.idField = value;
                        this.RaisePropertyChanged("id");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string name {
                get {
                    return this.nameField;
                }
                set {
                    if ((object.ReferenceEquals(this.nameField, value) != true)) {
                        this.nameField = value;
                        this.RaisePropertyChanged("name");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.marcura.com/dis/notifications", ConfigurationName="NotificationPoller.NotificationPoller")]
    public interface NotificationPoller {
        
        // CODEGEN: Generating message contract since element name principalId from namespace http://www.marcura.com/dis/notifications is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WindowsFormsApplication1.NotificationPoller.pollResponse poll(WindowsFormsApplication1.NotificationPoller.poll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.NotificationPoller.pollResponse> pollAsync(WindowsFormsApplication1.NotificationPoller.poll request);
        
        // CODEGEN: Generating message contract since element name credentials from namespace http://www.marcura.com/dis/notifications is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WindowsFormsApplication1.NotificationPoller.loginResponse login(WindowsFormsApplication1.NotificationPoller.login request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.NotificationPoller.loginResponse> loginAsync(WindowsFormsApplication1.NotificationPoller.login request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class poll {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="poll", Namespace="http://www.marcura.com/dis/notifications", Order=0)]
        public WindowsFormsApplication1.NotificationPoller.pollBody Body;
        
        public poll() {
        }
        
        public poll(WindowsFormsApplication1.NotificationPoller.pollBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.marcura.com/dis/notifications")]
    public partial class pollBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string principalId;
        
        public pollBody() {
        }
        
        public pollBody(string principalId) {
            this.principalId = principalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pollResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pollResponse", Namespace="http://www.marcura.com/dis/notifications", Order=0)]
        public WindowsFormsApplication1.NotificationPoller.pollResponseBody Body;
        
        public pollResponse() {
        }
        
        public pollResponse(WindowsFormsApplication1.NotificationPoller.pollResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dadesk.com/dis/schema")]
    public partial class pollResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.NotificationPoller.DaDeskEventNotificationsType daDeskEventNotifications;
        
        public pollResponseBody() {
        }
        
        public pollResponseBody(WindowsFormsApplication1.NotificationPoller.DaDeskEventNotificationsType daDeskEventNotifications) {
            this.daDeskEventNotifications = daDeskEventNotifications;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://www.marcura.com/dis/notifications", Order=0)]
        public WindowsFormsApplication1.NotificationPoller.loginBody Body;
        
        public login() {
        }
        
        public login(WindowsFormsApplication1.NotificationPoller.loginBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.marcura.com/dis/notifications")]
    public partial class loginBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.NotificationPoller.loginType credentials;
        
        public loginBody() {
        }
        
        public loginBody(WindowsFormsApplication1.NotificationPoller.loginType credentials) {
            this.credentials = credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://www.marcura.com/dis/notifications", Order=0)]
        public WindowsFormsApplication1.NotificationPoller.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(WindowsFormsApplication1.NotificationPoller.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.marcura.com/dis/notifications/schema")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WindowsFormsApplication1.NotificationPoller.userType user;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(WindowsFormsApplication1.NotificationPoller.userType user) {
            this.user = user;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NotificationPollerChannel : WindowsFormsApplication1.NotificationPoller.NotificationPoller, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationPollerClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.NotificationPoller.NotificationPoller>, WindowsFormsApplication1.NotificationPoller.NotificationPoller {
        
        public NotificationPollerClient() {
        }
        
        public NotificationPollerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificationPollerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationPollerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationPollerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.NotificationPoller.pollResponse WindowsFormsApplication1.NotificationPoller.NotificationPoller.poll(WindowsFormsApplication1.NotificationPoller.poll request) {
            return base.Channel.poll(request);
        }
        
        public WindowsFormsApplication1.NotificationPoller.DaDeskEventNotificationsType poll(string principalId) {
            WindowsFormsApplication1.NotificationPoller.poll inValue = new WindowsFormsApplication1.NotificationPoller.poll();
            inValue.Body = new WindowsFormsApplication1.NotificationPoller.pollBody();
            inValue.Body.principalId = principalId;
            WindowsFormsApplication1.NotificationPoller.pollResponse retVal = ((WindowsFormsApplication1.NotificationPoller.NotificationPoller)(this)).poll(inValue);
            return retVal.Body.daDeskEventNotifications;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.NotificationPoller.pollResponse> WindowsFormsApplication1.NotificationPoller.NotificationPoller.pollAsync(WindowsFormsApplication1.NotificationPoller.poll request) {
            return base.Channel.pollAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.NotificationPoller.pollResponse> pollAsync(string principalId) {
            WindowsFormsApplication1.NotificationPoller.poll inValue = new WindowsFormsApplication1.NotificationPoller.poll();
            inValue.Body = new WindowsFormsApplication1.NotificationPoller.pollBody();
            inValue.Body.principalId = principalId;
            return ((WindowsFormsApplication1.NotificationPoller.NotificationPoller)(this)).pollAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.NotificationPoller.loginResponse WindowsFormsApplication1.NotificationPoller.NotificationPoller.login(WindowsFormsApplication1.NotificationPoller.login request) {
            return base.Channel.login(request);
        }
        
        public WindowsFormsApplication1.NotificationPoller.userType login(WindowsFormsApplication1.NotificationPoller.loginType credentials) {
            WindowsFormsApplication1.NotificationPoller.login inValue = new WindowsFormsApplication1.NotificationPoller.login();
            inValue.Body = new WindowsFormsApplication1.NotificationPoller.loginBody();
            inValue.Body.credentials = credentials;
            WindowsFormsApplication1.NotificationPoller.loginResponse retVal = ((WindowsFormsApplication1.NotificationPoller.NotificationPoller)(this)).login(inValue);
            return retVal.Body.user;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.NotificationPoller.loginResponse> WindowsFormsApplication1.NotificationPoller.NotificationPoller.loginAsync(WindowsFormsApplication1.NotificationPoller.login request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.NotificationPoller.loginResponse> loginAsync(WindowsFormsApplication1.NotificationPoller.loginType credentials) {
            WindowsFormsApplication1.NotificationPoller.login inValue = new WindowsFormsApplication1.NotificationPoller.login();
            inValue.Body = new WindowsFormsApplication1.NotificationPoller.loginBody();
            inValue.Body.credentials = credentials;
            return ((WindowsFormsApplication1.NotificationPoller.NotificationPoller)(this)).loginAsync(inValue);
        }
    }
}
